name: "CI workflow"
on:
  push:
    branches:
      - dev
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      - name: Validate
        run: terraform fmt -recursive && terraform init -backend=false && terraform validate
        
